[build-system]
requires = [
“setuptools>=42”,
“wheel”
]
build-backend = “setuptools.build_meta”


[project]
name = "annual_report"
version = "0.0.2"
authors = [
  { name="Darix SAMANI", email="samanidarix@gmail.com" },
]
description = "the objectives of this project, is to retrieve all annual report documents on a given website"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Bug Tracker" = "https://github.com/darixsamani/annual_report/issues"